### PR TITLE
fix(colors): convert rgba/hsla to rgb/hsl if opacity is >= 1

### LINKED ISSUE #1082: optimizeColors: rgba|hsla with opacity >=1.0 should change to rgb|hsl
### Environment

* clean-css version - 4.2.1:
* node.js version - 10.16.0:
* operating system: Windows 10 / Ubuntu 18

### Configuration options

```
var CleanCSS = require('clean-css');
new CleanCSS({
   level: 2
})
```

### Input CSS

```
.a { color: rgba(255, 255, 255, 1); }
.b { color: hsla(0, 100%, 50%, 1); }
.c { color: RGB(255, 255, 255); }
.d { color: HSL(0, 100%, 50%); }
```

### Actual output CSS

```
.a{color:rgba(255,255,255,1)}.b{color:hsla(0,100%,50%,1)}.c{color:RGB(255,255,255)}.d{color:HSL(0,100%,50%)}
```

### Expected output CSS

```
.a{color:#fff}.b{color:red}.c{color:#fff}.d{color:red}
```

I also noticed that color parsing is case-sensitive when they shouldn't be. It's messing up some SCSS code I'm using. In SCSS, `rgb()` is an internal function so I use `RGB()` instead. `clean-css` doesn't pick it up. PR coming up.

### PR DESCRIPTION
**Pull request by clshortfuse**
fixes #1082

Fixes:
 * `rgba(R,G,B,1)` => `rgb(R,G,B)`
 * `rgb(R,G,B,1)` => `rgb(R,G,B)`
 * `hsla(H,S,L,1)` => `hsl(H,S,L)`
 * `hsl(H,S,L,1)` => `hsl(H,S,L)`
 * Removes case-sensitivity for `rgb`, `rgba`, `hsl`, and `hsla`

For reference, CSS 4 supports alpha parameter for `rgb()` and `hsl()`. That's why the new regex is also optionally looking for `a`. If it finds it and opacity is 1, then it effectively removes the alpha parameter. That's a plus for backwards compatibility for browsers that don't support `rgb(R G B A)`.

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

### CODE REVIEW

File: lib/optimizer/level-1/optimize.js [hunk 1]
```diff
@@ -89,16 +89,25 @@ function optimizeBorderRadius(property) {
...
 
+/**
+ * @param {string} name
+ * @param {string} value
+ * @param {Object} compatibility
+ * @return {string}
+ */
 function optimizeColors(name, value, compatibility) {
-  if (value.indexOf('#') === -1 && value.indexOf('rgb') == -1 && value.indexOf('hsl') == -1) {
+  if (!value.match(/#|rgb|hsl/gi)) {
```
Comment (jakubpawlowicz) [inline lib/optimizer/level-1/optimize.js]: I wonder if this change may lead to a slight performance degradation, but let's merge it and fix if needed.

**Comment by clshortfuse** [comment]
I haven't looked at this PR in a bit, but the Regex may be incorrect and could cause issues.

The proper Regex for numbers is `/[+-]?((\d+)|(\d*\.\d+))(e[+-]?\d+)?/`. That covers all the requirements in the CSS spec.

I made a crazy long Regex that can verify CSS colors at https://gist.github.com/clshortfuse/acffca0a5f1412edcf9e132f33febe1c

Implementing one based along that may also fix other issues in clean-css that we aren't aware about (possibly supporting complex values like `rgb( 1.2e2, 5e-4, +2)`.

**Comment by clshortfuse** [comment]
After closer inspection, the regex is unlikely to cause issues, but could be better. I'm making a PR to support scientific notation as well RGB(% % %). But it's not as urgent as I previously thought.
