### PR TITLE
Prevent unquoting on grid elements

### LINKED ISSUE #1078: Quotes removed from single column grid definitions
If you define a single column CSS grid using the `grid` property (instead of the explicit grid-template-areas/rows/columns), the quotes get removed from the the grid area names which results in invalid CSS (as far as I can tell).  

The minified CSS fails to render properly in both Chrome and Firefox whereas the regular CSS renders as expected.  Quotes are NOT removed when using `grid-template-areas` property which was fixed in #917.

Note: I'm running this through gulp, but I don't have any special configuration for clean-css.  I can figure out how to do it directly if necessary.

### Environment

* clean-css version - `npm ls clean-css`: 4.2.1
* node.js version - `node -v`: 12.3.1
* operating system: Windows

### Configuration options

```js
const { src, dest, series, } = require('gulp');
const rename = require('gulp-rename');
const cleanCSS = require('gulp-clean-css');

const minifyCss = () => {
    return src('./test.css')
        .pipe(cleanCSS({ rebase: false }))
        .pipe(rename({
            suffix: '.min'
        }))
        .pipe(dest(f => f.base));
}

exports.default = series(minifyCss);
```

### Input CSS

```css
#wrapper {
    display: grid;
    grid:
        "logo" auto
        "nav" auto
        "content" 1fr
        / 1fr;
}
```

### Actual output CSS

```css
#wrapper{display:grid;grid:logo auto nav auto content 1fr/1fr}
```

### Expected output CSS

```css
#wrapper{display:grid;grid:"logo" auto "nav" auto "content" 1fr/1fr}
```

### PR DESCRIPTION
**Pull request by veleek**
Add "grid" element to list of elements ignored by removeQuotes.
This prevents required quotes from being removed from single column grids.

Fixes #1078

### CODE REVIEW

File: lib/optimizer/level-1/optimize.js [hunk 1]
```diff
@@ -336,7 +336,7 @@ function optimizeZeroUnits(name, value) {
 }
 
 function removeQuotes(name, value) {
-  if (name == 'content' || name.indexOf('font-variation-settings') > -1 || name.indexOf('font-feature-settings') > -1 || name.indexOf('grid-') > -1) {
+  if (name == 'content' || name.indexOf('font-variation-settings') > -1 || name.indexOf('font-feature-settings') > -1 || name == "grid" || name.indexOf('grid-') > -1) {
```
Comment (jakubpawlowicz) [inline lib/optimizer/level-1/optimize.js]: Hey @veleek - please use single quotes in "grid" as otherwise linter fails. Otherwise it looks good!

**Comment by jakubpawlowicz** [comment]
Sorry it took a moment, but I only had time to review it now. Let's merge it.

**Comment by veleek** [comment]
No worries, thanks for the merge!
